name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
                    
          commits_authoring: Tenclea, 62174952+Tenclea@users.noreply.github.com
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          config_timezone: Europe/Paris
          filename: assets/github-metrics.*
          optimize: css, xml
          user: Tenclea
          
          retries: 5
          retries_delay: 600
                    
          retries_output_action: 5
          retries_delay_output_action: 120
          
          template: classic
          base: header, repositories
          base_hireable: yes
          
          # Displays nb of added/removed lines of code
          plugin_lines: yes
          
          # Display nb of users visiting repositories
          plugin_traffic: yes
          
          # Displays starred topics
          plugin_topic: yes
          plugin_topics_mode: icons
          
          # Displays recently starred repositories
          plugin_stars: yes
          plugin_stars_limit: 3
          
          # Displays stargazers evolution over the last two weeks
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic  # available: classic, chartist
          
          # Displays a list of pinned repositories
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          
          # Displays commit calendar across several years
          # plugin_calendar: yes
          # plugin_calendar_limit: 11
          
          # Displays coding habits based on recent activity
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          
          # Displays the ratio of open/closed issues and open/merged pull requests across GitHub
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories, user
