name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          optimize: css, xml
          
          retries: 5
          retries_delay: 600
                    
          retries_output_action: 5
          retries_delay_output_action: 120
          
          
